defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: toxicbakery/alpine-glibc-android:release-1.2.0
  environment:
    TERM: dumb

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Execute Gradle
          command: |
            echo "zipCodeAndCountryCode=${ZIP_CODE_AND_COUNTRY}" >> local.properties
            echo "newsFeedUrl=https\://news.google.com/news/rss/" >> local.properties
            echo "calendarIcalUrl=${ICAL_URL}" >> local.properties
            echo "openWeatherApiKey=${OPEN_WEATHER_API_KEY}" >> local.properties
            echo "org.gradle.parallel=false" >> gradle.properties
            echo "kotlin.incremental=false" >> gradle.properties
            ./gradlew build check --no-daemon -PdisablePreDex

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: Sonatype
          filters:
            tags:
              only: /.*/
